# This dataset config is for weekly pulls of the National Immunization
# Survey Adult COVID Module: Respondent Vaccination View dataset on data.cdc.gov
#  'https://data.cdc.gov/Vaccinations/National-Immunization-Survey-Adult-COVID-Module-NI/si7g-c2bs/about_data'

############################################################################

[properties]
# The name field is the only required field here. Though other
# files can be accessed in the datacat by key/name.

name = "covid_survey_resp_vax_view"
automate = false
type = "etl"

############################################################################

[source]
# These source fields are open to being changed based on the source type
# and api requirements. This example uses a Socrata data source
# which is common for CDC data sources.

domain = "data.cdc.gov"
id = "si7g-c2bs"
limit = 10000

############################################################################

[extract]
# These are the details of where to store the raw extracted data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/mcmv/raw/covid_survey_resp_vax_view"

############################################################################

[load]
# These are the details of where to store the transformed and loaded data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/mcmv/transformed/covid_survey_resp_vax_view"

############################################################################

# Changelog
# ---------
# 2026-05-05: Initial version created by Ryan Raasch
