# This dataset config is for weekly pulls of the Weekly Parental Intent 
# for Vaccination
# 'https://data.cdc.gov/Child-Vaccinations/Weekly-Parental-Intent-for-Vaccination-and-Cumulat/ker6-gs6z/about_data'

############################################################################

[properties]
# The name field is the only required field here. Though other
# files can be accessed in the datacat by key/name.

name = "parental_vax_intent_weekly"
type = "etl"

############################################################################

[source]

domain = "data.cdc.gov"
id = "ker6-gs6z"
limit = 10000

############################################################################

[extract]
# These are the details of where to store the raw extracted data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/mcmv/raw/parental_vax_intent_weekly"

############################################################################

[load]
# These are the details of where to store the transformed and loaded data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = ""
container = ""
prefix = "dataops/mcmv/transformed/parental_vax_intent_weekly"

############################################################################

# Changelog
# ---------
# 2026-05-05: Initial version created by Ryan Raasch
