# This is the nssp latest comprehensive dataset.

############################################################################

[properties]
# The name field is the only required field here. Though other
# files can be accessed in the datacat by key/name.

name = "comprehensive_nssp_gold"
type = "reference"

############################################################################

[source]

storage_location.account = "cfaazurebatchprd"
storage_location.container = "nssp-etl"

############################################################################

[load]
# These are the details of where to store the reference data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = "" # use default
container = "" # use default
prefix = "dataops/stf/transformed/comprehensive_nssp_gold/"

############################################################################

# Changelog
# ---------
# 2026-03-04: Initial version created by Ryan Raasch (xng3)
# 2026-03-09: Changed name to comprehensive_nssp_gold
