# This is an example dataset configuration file for the dataops create_catalog tool.
# It is designed to represent the data provenance of reference data that can be used
# on multiple projects. Reference data is typically static or changes infrequently.
# Thus, it is not necessary to store the raw extracted data, only the transformed

############################################################################

[properties]
# The name field is the only required field here. Though other
# files can be accessed in the datacat by key/name.

name = "nssp_gold"
type = "experiment"

############################################################################

[source]

storage_location.account = "cfaazurebatchprd"
storage_location.container = "nssp-etl"
storage_location.prefix = "gold/"

############################################################################

[load]
# These are the details of where to store the reference data.
# If not included or given an empty string, the defaults in the
# catalog_defaults.toml will be used

account = "" # use default
container = "" # use default
prefix = "dataops/public/stf/nssp_gold/"

############################################################################

# Changelog
# ---------
# 2025-10-06: Initial version created by Phil Rogers (ap66)
